### ISSUE TITLE
GZDoom ini file ignored

### ISSUE THREAD

**Issue by Dapuva76** [flathub/io.github.Youda008.DoomRunner#3]
I'm on Fedora 38 and installed both GZDoom as well as Doom Runner through flatpak. I've given both apps permission to read the file system, via Flatseal. GZDoom by itself runs just as expected, but when it gets launched through Doom Runner, it complains that it can't find any IWADS, and I should modify the .ini file to point to the directories (I have).

**Comment by mbugni** [comment]
Hi, remember that Doom Runner app comes with its own embedded GZDoom.

So, if I well understand, you want to configure the GZDoom app as an [additional engine](https://github.com/flathub/io.github.Youda008.DoomRunner#add-a-flatpak-engine).

Please, provide more details about your environment:
1. did you [grant permissions to the engine](https://github.com/flathub/io.github.Youda008.DoomRunner#1---grant-permissions)?
2. did you [create a launcher script for the engine](https://github.com/flathub/io.github.Youda008.DoomRunner#2---create-a-launcher-script)?
3. did you [add the sandboxed engine properly](https://github.com/flathub/io.github.Youda008.DoomRunner#3---add-the-engine)?
